name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm install -g wait-on cypress

      - name: Run Django migrations
        run: python manage.py migrate

      - name: Start Django server
        run: |
          nohup python manage.py runserver 0.0.0.0:8080 &
        env:
          DJANGO_SETTINGS_MODULE: Project.settings  # adapte si ton module est différent

      - name: Wait for Django to be ready
        run: wait-on http://localhost:8080/home

      - name: Run Cypress tests
        run: npx cypress run --browser chrome
